services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: wine_api
    ports:
      - "8000:8000"
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: wine_app
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: unless-stopped
